- ansible.builtin.set_fact:
    db_name: "{{ db.name | replace('-','_') }}"

- ansible.builtin.set_fact:
    db_password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=db_name) }}"

- community.hashi_vault.vault_kv2_get:
    url: "{{ vault_url }}"
    path: "{{ app_path }}_db_{{ db_name }}"
    engine_mount_point: "{{ realm }}"
    auth_method: approle
    role_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID', default='nobody') }}"
    secret_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_SECRET_ID', default='nobody') }}"
  register: response
  ignore_errors: true

- community.hashi_vault.vault_write:
    url: "{{ vault_url }}"
    path: "{{ realm }}/data/{{ app_path }}_db_{{ db_name }}"
    data:
      data:
        db_host: "{{ db_host }}"
        db_port: "{{ db_port }}"
        db_name: "{{ db_name }}"
        db_user: "{{ db_name }}"
        db_password: "{{ db_password }}"
    auth_method: approle
    role_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_ID', default='nobody') }}"
    secret_id: "{{ lookup('ansible.builtin.env', 'VAULT_ROLE_SECRET_ID', default='nobody') }}"
  when: response.msg is defined and "Invalid or missing path" in response.msg

- name: Make sure "{{ db_name }}" user are present
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ db_name }}"
    password: "{{ db_password }}"
    login_port: "{{ db_port }}"
  delegate_to: "{{ db_host }}"

- name: Make sure "{{ db_name }}" database are present
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ db_name }}"
    login_port: "{{ db_port }}"
  delegate_to: "{{ db_host }}"

- name: Allow connect role "{{ db_name }}" to database "{{ db_name }}" with pg_hba.conf
  become: true
  become_user: postgres
  community.postgresql.postgresql_pg_hba:
    dest: "/etc/postgresql/{{ rdbms.db_version | default(rdbms_default.db_version) }}/{{ db_group }}/pg_hba.conf"
    contype: host
    users: "{{ db_name }}"
    databases: "{{ db_name }}"
    method: scram-sha-256
    source: 10.0.0.0/8
    keep_comments_at_rules: true
    comment: "this rule from deploy role / db.yml"
  delegate_to: "{{ db_host }}"
  register: allow_connect

- name: Reload config when allow_connect
  become: true
  ansible.builtin.command: "/usr/bin/pg_ctlcluster {{ rdbms.db_version | default(rdbms_default.db_version) }} {{ db_group }} reload"  
  delegate_to: "{{ db_host }}"
  when: allow_connect.changed

- name: "Add extension to database"
  become: true
  become_user: postgres
  community.postgresql.postgresql_ext:
    db: "{{ db_name }}"
    name: "{{ extension }}"
    schema: public
    login_port: "{{ db_port }}"
  loop: "{{ db.ext }}"
  loop_control:
    loop_var: extension
  delegate_to: "{{ db_host }}"
