- ansible.builtin.set_fact:
    db_host: "{{ rdbms_servers[item.host] }}"

- ansible.builtin.set_fact:
    db_port: "{{ item.port }}"

- ansible.builtin.set_fact:
    app_path_as_list: "{{ app_path | split('/') }}"

- ansible.builtin.set_fact:
    db_group: "{{ app_path_as_list | reject('search', app_path_as_list[-1]) | join('-') }}"
  when: item.group is not defined

- ansible.builtin.set_fact:
    db_group: "{{ item.group }}"
  when: item.group is defined

- ansible.builtin.include_tasks: db.yml
  loop: "{{ item.databases }}"
  loop_control:
    loop_var: db

- ansible.builtin.include_tasks: db_user.yml
  loop: "{{ item.users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
