pgbackrest_retention_full: 30

pgbackrest_repo_s3_bucket: "pgbackrest-rdbms"
pgbackrest_repo_s3_endpoint: "https://storage.yandexcloud.net/"
pgbackrest_repo_s3_region: "ru-central1"
pgbackrest_repo_s3_key: ""
pgbackrest_repo_s3_key_secret: ""
pgbackrest_repo_s3_uri_style: "host"
pgbackrest_repo_s3_verify_tls: "y"