---
disk_type: bronze
pg_name: main
pg_version: 16
pg_data_dir: "/var/lib/postgresql/{{ pg_version }}/{{ pg_name }}"
pg_conf_dir: "/etc/postgresql/{{ pg_version }}/{{ pg_name }}"
pg_port: 5432
pg_encoding: UTF8
pg_locale: en_US.UTF-8
pg_password_encryption_algorithm: scram-sha-256

pg_unix_socket_dir: /var/run/postgresql

replicator_password: 'doo6icaep0ooLuokae'

replica_enabled: True

postgresql_pg_hba: []

default_backups:
  - type: full
    oncalendar: "OnCalendar=*-*-* 23:00:00"
  - type: incr
    oncalendar: |
      OnCalendar=*-*-* 07:00:00
      OnCalendar=*-*-* 11:00:00
      OnCalendar=*-*-* 16:00:00

ssh_key_name: "postgres-ssh-key"
ssl_cert_days: 3650

port_scheme:
  level:
    erp: 1
    oa: 2
    inf: 3
  erp_system:
    core: 0
    mgmt: 1
    skm: 2
    kb: 3
  erp_core_subsytem:
    prs: 0
    ins: 1
    pas: 2
    vrs: 3
  erp_mgmt_subsystem:
    land: 0
    design: 1
    order: 2
    sales: 3
    finance: 4
    organization: 5
    development: 6
    rnd: 7
  oa_system:
    land: 00
    pc: 01
    design: 02
    construction: 03
    order: 04
    sc: 05
    sales: 06
    marketing: 07
    finance: 08
    organization: 09
    development: 10