---
# defaults file for deploy
realm: "{{ lookup('env', 'REALM') | default('staging', True) }}"

region: "nomad-gld"
datacenter:
  staging:
    - "nomad-gld-stg-1"
  rc:
    - "nomad-gld-rc-1"
  production:
    - "nomad-gld-1"
  brusnica:
    - "tur-1"

http_port_default:
  http:
    to: 80
api_port_default:
  api:
    to: 3000

containers_default:
  frontend:
  backend:
    configs:
      - config.yaml

proxy_default:
  locations:
    - name: /
      container: frontend
    - name: /backend/
      container: backend

image_version: latest
repo_url:
  staging: "snapshot-repo.brusnika.tech/brusnika/"
  rc: "rc-repo.brusnika.tech/brusnika/"
  production: "release-repo.brusnika.tech/brusnika/"
  brusnica: "release-repo.brusnika.tech/brusnika/"

resources:
  cpu        : 10
  memory     : 50
  memory_max : 100

resources_backend:
  cpu        : 200
  memory     : 100
  memory_max : 200

dns_servers  : ["10.176.0.2"]
dns_searches : ["brusnika.ltd"]

artifact_private_key_name  : id_gitlab
artifact_configs_repo_name : "{{ lookup('env', 'CONFIGS_REPO') | default('deploy/brusnika', True) }}"
artifact_configs_repo_uri  : "gitlab.brusnika.tech:/{{ artifact_configs_repo_name }}"

branch:
  staging: "master"
  rc: "release-candidate"
  production: "release"
  brusnica: "release"

rdbms_default:
  db_version: 16

sso_realm:
  staging: "Staging"
  rc: "RC"
  production: "Brusnika"
  brusnica: "production"
keycloak_url: https://login.brusnika.ru

restart: true

domain_name: brusnika
consul_zone: service.bru
